### ISSUE TITLE
igraph error

### ISSUE THREAD

**Issue by sohitmiglani** [CostaLab/CrossTalkeR#3]
Hello, 

I was running your software on my data when I came across the following error (below). How do I resolve this ?

R[write to console]: Reading Files

CTR 
"filtered_corrected.csv" 
[1] 6
EXP 
"filtered_corrected.csv" 
[1] 6
R[write to console]: Create a Differential Table

R[write to console]: Error in igraph::`E<-`(`*tmp*`, value = `*vtmp*`) : invalid indexing
Calls: <Anonymous> ... generate_report -> create_diff_table_wip -> <Anonymous>

R[write to console]: In addition: 
R[write to console]: Warning message:

R[write to console]: In max(table(final_data$cellpair)) :
R[write to console]: 
 
R[write to console]:  no non-missing arguments to max; returning -Inf

**Comment by jsnagai** [comment]
Hi @sohitmiglani, Can you check the following

1 - if you are using the following characters in celltype name: '_' and  '\' 
2 - if you have any missing values (NA) on your input table
3 - if in your "MeanLR" you are using '.' or ',' to separate the decimals

Also, is it possible to you share how you are using the CrossTalkeR?

Best
