### ISSUE TITLE
mouse/human gene symbols in CrosstalkeR

### ISSUE THREAD

**Issue by Wulin-Tan** [CostaLab/CrossTalkeR#41]
Hi, 
CrosstalkeR is a great tool for our projects.
I tried the human data and it worked perfect well. but when I tried mouse genes, it seemed to fail to read the gene symbol.
Is it compatible with mouse genes now? or any way to make it work for mouse genes?
Thank you.

below is the error showed in my running:
Annotating the top Cell Genes
'select()' returned 1:many mapping between keys and columns
Error in .testForValidKeys(x, keys, keytype, fks) : 
  None of the keys entered are valid keys for 'SYMBOL'. Please use the keys method to see a listing of valid arguments.

**Comment by jsnagai** [comment]
Dear @Wulin-Tan,

Im more than happy to know that our tool is working for you. We are currently improving CrossTalkeR and a small release might be available by the end of the week.

Hope that it fits to you
Best

**Comment by jsnagai** [comment]
the murine data annotation was added to the package
