### ISSUE TITLE
Error when compare two group

### ISSUE THREAD

**Issue by xiasijian** [CostaLab/CrossTalkeR#43]
![image](https://user-images.githubusercontent.com/39158528/184564226-20979801-abf2-48f2-8062-476d8abe9069.png)

Hello, when I run the function named generate_report, this error happened. Thank you.

**Comment by jsnagai** [comment]
Hi @xiasijian can you try to run the same code, but set the report to false, report=F. This gonna tell us where is the problem basically.

Best

**Comment by xiasijian** [comment]
Thanks, I have solved it.
