### ISSUE TITLE
Dependency ‘Rmagic’ is no longer available 

### ISSUE THREAD

**Issue by robpade** [CostaLab/CrossTalkeR#46]
"Package ‘Rmagic’ was removed from the CRAN repository."
See message here: https://cran.r-project.org/web/packages/Rmagic/index.html

When I try to install CrossTalkeR, I get the following related error:

> Downloading GitHub repo CostaLab/CrossTalkeR@HEAD
> Skipping 1 packages not available: Rmagic
> ── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────────
> ✔  checking for file ‘/private/var/folders/zd/k6yfv3zs6n16n5x92kl74vtr0000gn/T/RtmpodZlpM/remotes28201ad4d828/CostaLab-CrossTalkeR-894b346/DESCRIPTION’ ...
> ─  preparing ‘CrossTalkeR’:
> ✔  checking DESCRIPTION meta-information ...
> ─  installing the package to build vignettes
>          -----------------------------------
>    ERROR: dependency ‘Rmagic’ is not available for package ‘CrossTalkeR’
> ─  removing ‘/private/var/folders/zd/k6yfv3zs6n16n5x92kl74vtr0000gn/T/RtmpJBUMLD/Rinst2cc02f5748e1/CrossTalkeR’
>          -----------------------------------
>    ERROR: package installation failed
> Error: Failed to install 'CrossTalkeR' from GitHub:
>   ! System command 'R' failed

I tried using what I believe to be the related GitHub (https://github.com/cran/Rmagic), but was unsuccessful. Is there a workaround, or plans to remove dependency of CrossTalkeR on RMagic?

**Comment by jsnagai** [comment]
Dear @robpade,

We are working with updates in CrossTalkeR and this dependency will be removed in the next commit. i should do a update tomorrow in the package lrtf-devel branch...this might solve the issue

**Comment by jsnagai** [comment]
Dear @robpade the update is done...can you try it out?

Just a small change, if you are using the genes you might use

genes <- c('TGFB1|L') 

by now.

Best

**Comment by robpade** [comment]
@jsnagai your update works on my end, I successfully installed the package. Thank you!

I'll be testing this out soon, but can't today unfortunately.
