### ISSUE TITLE
which LR analysis tools does CrossTalkeR work with?

### ISSUE THREAD

**Issue by me37uday** [CostaLab/CrossTalkeR#54]
Hi,

Thanks for your tool. Really appreciate the idea of looking into differential LR interaction based on conditions!

I am having a hard time running it using the output of cellchat. So I thought of running cellphoneDB first, as mentioned in the tutorial. However, I am stuck again and I have a feeling that the workflow of cellphoneDB has changed overtime. The latest version of cellphoneDB does not work the same as it's predecessors. It cannot be used as an executable on command line as mentioned in the tutorial here. Please correct me if I am wrong.

In case of the output from cellchat, I have organised the input as shown in the tutorial for both CTR and EXP but I get the following error : 

```
data <- generate_report(paths,
                         genes,
                         out_path=paste0(output,'/'),
                         threshold=0,
                         out_file = 'vignettes_example.html',
                         output_fmt = "html_document",
                         report = FALSE)

Reading Files
Error in `dplyr::mutate()`:
ℹ In argument: `ccitype = paste(data1[[sel_columns[5]]], data1[[sel_columns[6]]])`.
Caused by error:
! `ccitype` must be size 2863 or 1, not 0.
Run `rlang::last_trace()` to see where the error occurred.

```
 
Here's a snapshot of the input :  

<!DOCTYPE html>

<html>
<head>
	
	
	
</head>

<body>

  | source | target | gene_A | gene_B | gene_type_A | gene_type_B | MeanLR
-- | -- | -- | -- | -- | -- | -- | --
1 | Cranial neural crest | Neural 3 | wnt5b | fzd10 | Ligand | Receptor | 0.000714393318220126
2 | Cranial neural crest | Cranial neural crest | wnt5b | fzd2 | Ligand | Receptor | 0.000260300985644489
3 | Cranial neural crest | Pharyngeal mesenchyme | wnt5b | fzd2 | Ligand | Receptor | 0.000462609689846343
4 | Cranial neural crest | Sox10+ neural crest | wnt5b | fzd2 | Ligand | Receptor | 0.000228502229095687
5 | Cranial neural crest | Eye | wnt5b | fzd3a | Ligand | Receptor | 9.15492336721415E-05

</body>

</html>

Is this because of the zebrafish genes? Or is it something else? Please let me know. I will be happy to help you with more information from my end if needed!

Cheers.

**Comment by jsnagai** [comment]
Dear @me37uday thank you for considering our package, I'm not totally sure but this might have to do with our package design. In principle, we only considered its usage in human and murine models. We can add the zebrafish data in our next release, we are aiming to do a new release by the end of the next week

**Comment by me37uday** [comment]
Thanks for the update. Looking forward to the upgrade!

Cheers!
