### ISSUE TITLE
CellPhoneDB Analysis Hangs up in Python

### ISSUE THREAD

**Issue by jawinks** [CostaLab/CrossTalkeR#57]
Hello,

I am trying to generate the liana report. Firstly, I am a bit confused because I can't find in the CrossTalkeR documentation or the liana documentation where it explains how to generate a report for use in CrossTalkeR by using R and not python. 

Anyway, when I run the following code block from the HumanFibrosis.rmd vignette, with the fields from my object in place of the generic listing: 

``` 
for i in set(data.obs['condition']):
    print(i)
    lr=li.method.cellphonedb(data[data.obs['condition']==i],
                          groupby='cell.type',
                          expr_prop=0.1,
                          verbose=True,
                          resource_name='consensus',
                          inplace=False)
    lr.to_csv(f"{i}_lr_liana_consensus_unfiltered.csv")
```

The python module just hangs up and nothing happens. Any advice would be appreciated.

**Comment by vckraemer** [comment]
Hi @jawinks,

we don't provide a tutorial to run liana in R, because the performance in python is much better and we advise to use python to run this part.

Can you provide more information on how you read your object in python? It is hard to tell from the snippet why this code might get stuck.

**Comment by jawinks** [comment]
Thank you for the response. I will share my complete steps to better help understand this issue. 

```
import scanpy as sc
import liana as li
import pandas as pd
import os

data = sc.read_h5ad("C:\\...\\ssclung.h5ad")
data.raw = data

for i in set(data.obs['condition']):
    print(i)
    lr=li.method.cellphonedb(data[data.obs['condition']==i],
                          groupby='cell.type',
                          expr_prop=0.1,
                          verbose=True,
                          resource_name='consensus',
                          inplace=False)
    lr.to_csv(f"{i}_lr_liana_consensus_unfiltered.csv")

```

For some reason, running the last block of code is what causes the hang. Would it have something to do with the names I am using for the condition and cell type? I used the exact labels that are in my sce object before I converted it to anndata. 

Thanks!
