### ISSUE TITLE
Error in reading file while using vignette

### ISSUE THREAD

**Issue by s-yadav21** [CostaLab/CrossTalkeR#9]
Hi,
I was trying to run the vignette on my data (two samples - primary tumor and metastatic) and I am getting following error:

`Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
In addition: Warning message:
In file(file, "rt") :
  file("") only supports open = "w+" and open = "w+b": using the former`

My data contains read counts- genes are rows and cells as columns.

**Comment by jsnagai** [comment]
Hi @s-yadav21, could you check if your csv is using comma(",") as separator? The generate_report function provides a field to set a different separator you can easily change it there.

**Comment by s-yadav21** [comment]
Hi @jsnagai 
Thank you very much for such prompt response. 
Yes my file is comma separated. I used "sep" parameter in generate_report function and I am getting this error. I can't figure out what am I doing wrong.

**Comment by jsnagai** [comment]
@s-yadav21 it's my pleasure to help!!!

Are you using any character in your cell type name?

**Comment by s-yadav21** [comment]
Yes the cell names are alphanumeric.

**Comment by jsnagai** [comment]
@s-yadav21 Sorry, I meant, do you use the following characters in cell type name: '_' and '\' ?

**Comment by s-yadav21** [comment]
Sorry I misunderstood the question, yes my cell types have a special character , colon ' : '

**Comment by s-yadav21** [comment]
I removed colon from the cell type names and tried using generate report function. Still getting same error.
`Reading Files
PT 
"" 
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
In addition: Warning message:
In file(file, "rt") :
  file("") only supports open = "w+" and open = "w+b": using the former`

**Comment by jsnagai** [comment]
@s-yadav21  Would it be possible to you paste the content of you variable path here? 

It seems to me that the input is somehow not available, it could happen due to several reasons. Could you double check if you paths to your input files are correct??

# Linux version
paths <- c('CTR' = "/home/usr/Documents/CrossTalkeR_test/control_lrgenes.csv",
                 'EXP' = "/home/usr/Documents/CrossTalkeR_test/exp_lrgenes.csv")
 # Windows 
paths <- c('CTR' = "C:/Users/usr/Documents/CrossTalkeR_test/control_lrgenes.csv",
                 'EXP' = "C:/Users/usr/Documents/CrossTalkeR_test/exp_lrgenes.csv")

**Comment by jsnagai** [comment]
@s-yadav21  Does it work?
